name: Develop Workflow

on:
  push:
    branches: [ develop ]

env:
  REGISTRY: ghcr.io
  OWNER_REPO: namnextx
  IMAGE_NAME: ghcr.io/namnextx/${{ github.event.repository.name }}
  ENV_DEPLOY: dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  development-ci-cd:
    environment: Development Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: true
          ref: develop
          path: main

      - name: Set up JDK 11
        if: success()
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Unit/Integration Test
        if: success()
        working-directory: main
        run: mvn -B verify

      - name: Package
        working-directory: main
        run: mvn package -DskipTests

      # Build and Push Docker image on Repository Github
      - name: Set up Docker Buildx
        if: ${{ success() }}
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        if: ${{ success() }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.SR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,prefix=${{ env.ENV_DEPLOY }}-

      - name: Build and push Docker image
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: main
          file: ./main/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: JAVA_OPTS=${{ secrets.DOCKER_JAVA_OPTIONS }}
